OUTPUTS = [{"Beijing", "COVID-19"},
		   {"Black Lives Matter"},
		   {"Atlanta", "Val Demings"},
		   {"Fauci", "ABC", "Powerhouse Politics"},
		   {"John Bolton", "Trump White House"},
		   {"Black Americans", "COVID"},
		   {"BP"},
		   {"Trump", "Lincoln", "Carson"},
		   {"Supreme Court", "LGBT"},
		   set(),
		   {"West", "East"},
		   {"WHO"},
		   {"Trump", "California"},
		   {"Coronavirus", "Carmageddon"},
		   set(),
		   {"Trump", "coronavirus"},
		   set(),
		   {"Luke Bryan"},
		   {"Thomas", "Kavanaugh", "Second Amendment"},
		   {"Burgess Owens", "NFL"},
		   {"Milky Way"},
		   {"Chipotle"},
		   {"Twitter", "Band-Aid"},
		   {"N-word", "Stern"},
		   {"George Floyd"},
		   set(),
		   set(),
		   {"George Floyd Murals"},
		   {"NYC"},
		   {"Philadelphia", "Tomb of the Unknown Soldier"},
		   {"Siegel", "coronavirus"},
		   {"McDonald"},
		   {"BLM"}
		   ]