SENTENCES = ["Beijing braces for 2nd wave of COVID-19 infections",
			 "Video of man confronted by white couple for stenciling Black Lives Matter goes viral",
			 "Deadly force not 'only option' in Atlanta shooting: Rep. Val Demings",
			 "Fauci tells ABC's 'Powerhouse Politics' that attending rallies, protests is 'risky'",
			 "John Bolton's book recounts chaos, turmoil in Trump White House",
			 "Black Americans most likely to know a COVID victim"
			 "Energy producer BP takes $17.5b hit, demand down",
			 "'Not productive' to compare presidents, after Trump's Lincoln comparison: Carson",
			 "Supreme Court bans LGBT employment discrimination",
			 "Father, son beat and stab 12-year-old boy together",
			 "Wildfire danger in West, flooding rain in East",
			 "The Latest: WHO notes 100,000 new virus cases daily",
			 "Justices reject Trump bid to void California sanctuary law",
			 "Expert warns of 'Coronavirus Carmageddon' if returning workers avoid mass transit",
			 "Videos show man went from speaking of visiting mom's grave to being killed by police",
			 "Timeline: Trump’s response to the coronavirus pandemic",
			 "A silver-lining from quarantine: A renewed bond between fathers and children",
			  "Luke Bryan says his fans keep him grounded amid fame: 'I've always listened to what they had to say'",
			  "Thomas, Kavanaugh rip 'decade-long failure to protect Second Amendment'",
			  "Burgess Owens on NFL protests: 'It's about the flag, period!'",
			  "There could be more than 30 alien civilizations in the Milky Way, shocking study says",
			  "Mom takes maternity pics at Chipotle, calls chain 'saving grace' during pregnancy",
			  "Twitter responds to Band-Aid's new bandages for diverse skin tones: 'Took long enough'",
			  "GRAPHIC: Resurfaced blackface sketch, N-word use has Stern on ropes",
			  "PHOTOS: Death of George Floyd sparks widespread outcry, protests",
			  "Twins sisters become valedictorian and salutatorian at same high school",
			  "Planning to visit a national park? Here's what to know about reopening",
			  "Maskless woman at NYC bagel shop intentionally coughs on patron who calls her out",
			  "Philadelphia's Tomb of the Unknown Soldier statue defaced with graffiti: 'Committed GENOCIDE'",
			  "Dr. Siegel on uptick in coronavirus cases: Increased testing is 'not the whole story'",
			  ]